spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      filter:
        local-response-cache:
          enabled: true
          time-to-live: 10s
          size: 500
      routes:
        - id: customer_route
          uri: http://localhost:8085
          predicates:
            - Path=/api/customer/**
          filters:
            - RewritePath=/api/customer/(?<segment>.*), /customers/${segment}
            - LocalResponseCache
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
        - id: billing_route
          uri: http://localhost:8086
          predicates:
            - Path=/api/billing/**
          filters:
            - RewritePath=/api/billing/(?<segment>.*), /billings/${segment}
            - LocalResponseCache
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@userKeyResolver}"
server:
  port: 9090
